### ISSUE TITLE
Pauta

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/hangout#1]
# 01 - Mato Grosso e o PHP

## Pauta

- O que é e onde Usar PHP
- Por onde aprender PHP
- Por que usar boas praticas no PHP
- Quais Ferramentas ajudam no desenvolvimento
- Como ajudar e ser ajudado na Comunidade
- Mercado de Trabalho

**Comment by enieber** [comment]
massa..,  acho que para o primeiro pode ser um conteudo um pouco mais basico...

**Comment by jackmakiyama** [comment]
Acho legal dar um overview nos tópicos abordados no [PHP the right way](http://www.phptherightway.com/).

**Comment by jackmakiyama** [comment]
@enieber concordo.

Mas qual o publico? alguém que é dev e não conhece php, alguém que já trampa com php ou quem nunca programou?

**Comment by enieber** [comment]
acho q no primeiro momento quem já conhece PHP pra que possa contribuir mais com a comunidade daqui do Mato Grosso, em um segundo momento seria legal passar algo para quem nunca programou..

**Comment by jackmakiyama** [comment]
Então no primeiro seria mais apresentar o PHPMT para a comunidade?

**Comment by enieber** [comment]
basicamente..

**Comment by jackmakiyama** [comment]
Certo, nessa ideia então eu sugiro o titulo do primeiro ep como: **Mato Grosso e o PHP**

Alguma ideia mais para titulo?

**Comment by enieber** [comment]
perfeito...

**Comment by f0ntana** [comment]
Título Fechado, referente ao conteúdo, minha opinião é conhecer a comunidade, e apresentação, como o que trabalha as ferramentas, e tal, o qual dará ideias de outros encontros futuros...

**Comment by enieber** [comment]
acho q já da pra criar o arquivo README.md com a pauta @jackmakiyama

**Comment by jackmakiyama** [comment]
Certo!

@enieber calma moço... kkkkk, já está ali então vamos continuar, até definir.

é que penso assim, se for falar em boas práticas, vai ser complicado entender pq aquilo é uma boa pratica sem ter o exemplo de má prática, se entrar e paradigma vai ser algo um pouco extenso...

Esse tipo de coisa que estou pensando.
Deixar pra entrar nos méritos da linguagem em um próximo hangout, se não da um ep com mais de 1 hora que fica puxado pra galera assistir depois.

**Comment by VitorGGA** [comment]
Acho q poderia ter um espaço para cases, eh sempre legal ver o que algumas pessoas fizeram e como fizeram, acho q inspira mais \o

**Comment by jackmakiyama** [comment]
@VitorGGA boa! Cases aqui do Mato Grosso.. =D

**Comment by jackmakiyama** [comment]
Certo!

@enieber calma moço... kkkkk, já está ali então vamos continuar, até definir.

é que penso assim, se for falar em boas práticas, vai ser complicado entender pq aquilo é uma boa pratica sem ter o exemplo de má prática, se entrar e paradigma vai ser algo um pouco extenso...

Esse tipo de coisa que estou pensando.
Deixar pra entrar nos méritos da linguagem em um próximo hangout, se não da um ep com mais de 1 hora que fica puxado pra galera assistir depois.

**Comment by enieber** [comment]
Eai, fechou a **Pauta** ? podemos discutir qual sera o dia?

**Comment by jackmakiyama** [comment]
Pessoal, penso que nesse primeiro hangout vamos focar em Mato Grosso, apresentar a comunidade do PHP e algum case, não entrando na parte técnica da coisa.

O que me dizem?

**Comment by enieber** [comment]
um otimo começo

**Comment by f0ntana** [comment]
ReStart!

**Comment by jackmakiyama** [comment]
:metal:

**Comment by enieber** [comment]
lets go...ops, lets PHP

**Comment by f0ntana** [comment]
11/06 ?

**Comment by enieber** [comment]
Fecho então, 12/05 as 21:00 horario de Mato Grosso

**Comment by enieber** [comment]
ja da pra fechar essa issue e abrir uma nova não?

link do primeiro hangout 

https://www.youtube.com/watch?v=B-Z8JjutoyY

**Comment by f0ntana** [comment]
Show, vamos marcar os próximos.

Att.

**Comment by f0ntana** [comment]
top!


2016-10-21 13:34 GMT-03:00 Enieber Cunha <notifications@github.com>:
