### ISSUE TITLE
Logo para o PHP MT

### ISSUE THREAD

**Issue by enieber** [PHPMT/hangout#2]
Andei fazendo uns rabiscos pra logo do repositorio da comunidade PHP MT

O que acham da proposta ? 

https://github.com/enieber/logo-php-mt

**Comment by enieber** [comment]
como não tenho muita experiencia com design outras pessoas poderiam nos ajudar a fazer um  logo.

**Comment by f0ntana** [comment]
Vou te ajudar. :D não tenho muita experiencia tb mas tenho ideia.. quem sabe depois só melhoramos

**Comment by enieber** [comment]
algumas imagens para ajudar no desenvolvimento do logo
https://dribbble.com/enieber/buckets/435710-php-mt
